name: dart_nats
description: A Dart client for the NATS messaging system. Design to use with Dart and flutter.
version: 0.7.0
homepage: https://github.com/chartchuo
repository: https://github.com/chartchuo/dart-nats

environment:
  sdk: '>=3.10.0 <4.0.0'

# dependencies:

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  test: ^1.28.0
  very_good_analysis: ^10.0.0
  # pedantic: ^1.11.0
dependencies: 
  base32: ^2.1.3
  crypto: ^3.0.0
  ed25519_edwards: ^0.3.1
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.3
